spring:
  application:
    name: finance-app
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db
    username: postgres
    password: Applepie@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

